### ISSUE TITLE
Multiblock stage not working with latest IE

### ISSUE THREAD

**Issue by wormzjl** [The-Acronym-Coders/MultiBlock-Stages#10]
I have the following script:
`mods.multiblockstages.IEMultiBlockStages.addStage("blastfurnace_basic", "IE:BlastFurnace", "Need Research First");`

However I can form the multiblock even I don't have the required stage. Could this be induced by latest change in IE 0.12 - 92?

> - Added a second MultiblockFormEvent to the API, to fire *after* the structure has been checked (BluSunrize)

**Comment by SkySom** [comment]
Shouldn't have broken anything, but I plan to add switch to that event anyone once I get a few minutes (As literally Blu added that event at my request)

**Comment by wormzjl** [comment]
I did a test with build 91 and it works fine with that version :)
