### ISSUE TITLE
[Suggestion] Compatibility for Immersive Petroleum.

### ISSUE THREAD

**Issue by UnlimatedStone9** [The-Acronym-Coders/MultiBlock-Stages#8]
It's as simple as that, multiblock gating for IE's addon Immersive Petroleum.

**Comment by SkySom** [comment]
It should support anything properly registered to the Multiblock registry.

**Comment by Liiw** [comment]
Hello!

Can you confirm it works for you with Immersive Petroleum? I have just tried it and it lets me form the pumpjack for example. I have it staged properly and it is working with regular IE multiblocks.
