### ISSUE TITLE
[Suggestion] Compatibility for Immersive Tech.

### ISSUE THREAD

**Issue by UnlimatedStone9** [The-Acronym-Coders/MultiBlock-Stages#9]
It's as simple as that, multiblock gating for IE's addon Immersive Tech.

**Comment by SkySom** [comment]
It should support anything properly registered to the Multiblock registry.

**Comment by Liiw** [comment]
Hello!

Can you confirm it works for you with Immersive Tech? I have just tried it and it lets me form the Advanced Coke Oven for example. I have it staged properly and it is working with regular IE multiblocks.
